Added Alias support for Git Bash
devonfw-forge/rd-installer pull request #23
Opened 2022-04-08 09:39 UTC by abcarcol

2022-04-08 12:25 UTC, albertdb requested changes

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +    $search = (Get-Content $script:bashProfilePath | Select-String -Pattern '# generated by Rancher-Desktop for Alias support in Git Bash').Matches.Success
```suggestion
    $search = (Get-Content $script:bashProfilePath | Select-String -Pattern '# generated by rd-installer for Alias support in Git Bash').Matches.Success
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +        Add-Content $script:bashProfilePath "# generated by Rancher-Desktop for Alias support in Git Bash"
```suggestion
        Add-Content $script:bashProfilePath "# generated by rd-installer for Alias support in Git Bash"
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +    $search = (Get-Content $PROFILE | Select-String -Pattern '# generated by Rancher-Desktop for VPN support in Powershell').Matches.Success
```suggestion
    $search = (Get-Content $PROFILE | Select-String -Pattern '# generated by rd-installer for VPN support in Powershell').Matches.Success
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +        Add-Content $PROFILE "# generated by Rancher-Desktop for VPN support in Powershell"
```suggestion
        Add-Content $PROFILE "# generated by rd-installer for VPN support in Powershell"
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +    $search = (Get-Content $script:bashProfilePath | Select-String -Pattern '# generated by Rancher-Desktop for VPN support in Git Bash').Matches.Success
```suggestion
    $search = (Get-Content $script:bashProfilePath | Select-String -Pattern '# generated by rd-installer for VPN support in Git Bash').Matches.Success
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +        Add-Content $script:bashProfilePath "# generated by Rancher-Desktop for VPN support in Git Bash"
```suggestion
        Add-Content $script:bashProfilePath "# generated by rd-installer for VPN support in Git Bash"
```

2022-04-08 12:25 UTC, albertdb commented on install.ps1
> +        Add-Content $script:bashProfilePath "wsl -d wsl-vpnkit service wsl-vpnkit start 2> `$null"
Shouldn't be `/dev/null`?

2022-04-11 10:40 UTC, abcarcol commented on install.ps1
> +        Add-Content $script:bashProfilePath "wsl -d wsl-vpnkit service wsl-vpnkit start 2> `$null"
Yes, my bad.

2022-04-11 11:12 UTC, jbellver99 approved these changes

2022-04-12 07:40 UTC, albertdb commented on install.ps1
> +        Add-Content $PROFILE "wsl -d wsl-vpnkit service wsl-vpnkit start 2> `$null"
Is the backtick ` expected?

2022-04-12 07:53 UTC, abcarcol commented on install.ps1
> +        Add-Content $PROFILE "wsl -d wsl-vpnkit service wsl-vpnkit start 2> `$null"
Yes. it escapes the '$' character

2022-04-12 08:04 UTC, merged